# Generated by Django 4.0 on 2022-07-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='matches',
            new_name='match',
        ),
    ]
