# Generated by Django 4.0 on 2022-07-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0002_rename_matches_deliveries_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveries',
            name='matchid',
        ),
    ]
