# Generated by Django 4.0 on 2022-07-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0003_remove_deliveries_matchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='matchid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
