# Generated by Django 4.0 on 2022-07-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0004_deliveries_matchid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveries',
            name='matchid',
        ),
    ]
