# Generated by Django 4.0 on 2022-07-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0005_remove_deliveries_matchid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='match',
            new_name='match_id',
        ),
    ]
