# Generated by Django 4.0 on 2022-07-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0006_rename_match_deliveries_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveries',
            name='match_id',
        ),
        migrations.AddField(
            model_name='deliveries',
            name='match',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to='iplapp.matches'),
            preserve_default=False,
        ),
    ]
