# Generated by Django 4.0 on 2022-07-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0007_remove_deliveries_match_id_deliveries_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='id',
            new_name='match_id',
        ),
    ]
