# Generated by Django 4.0 on 2022-07-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0008_rename_id_matches_match_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='match_id',
            new_name='match',
        ),
    ]
